name: main

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        kubectx: [0.7.1]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Install Kubectx and print help
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add kubectx $GITHUB_WORKSPACE
          asdf install kubectx ${{ matrix.kubectx }}
          asdf global kubectx ${{ matrix.kubectx }}
          kubectx --help
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Test plugin
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-test kubectx $GITHUB_WORKSPACE 'kubectx --version' --asdf-tool-version ${{matrix.kubectx}}
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run ShellCheck
        run: shellcheck bin/*