name: main

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 5"

jobs:

  plugin_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        kubectl: [1.16.3]
        kubectx: [0.7.1]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install kubectl
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add kubectl
          asdf install kubectl ${{ matrix.kubectl }}
          asdf global kubectl ${{ matrix.kubectl }}
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          version: ${{ matrix.kubectx }}
          command: kubectx --help
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run ShellCheck
        run: shellcheck bin/*

